//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialApplicationQueries.Repositories.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommercialApplicationQueries.Repositories.Sql.OrderQueries", typeof(OrderQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT customer.name
        ///FROM commercialapplication.orders AS orders
        ///INNER JOIN  commercialapplication.orderscustomer AS orderscustomer ON orders.id = orderscustomer.orderid
        ///INNER JOIN  commercialapplication.customer AS customer ON orderscustomer.customerid = customer.id
        ///WHERE orders.id = @id;.
        /// </summary>
        internal static string GetCustomerName {
            get {
                return ResourceManager.GetString("GetCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT product.name as productname , orderitem.amount, orderitem.value
        ///FROM commercialapplication.orders AS orders
        ///INNER JOIN  commercialapplication.orderitemorders AS orderitemorders ON orders.id = orderitemorders.orderid
        ///INNER JOIN  commercialapplication.orderitem AS orderitem ON orderitemorders.orderitemid = orderitem.id
        ///INNER JOIN  commercialapplication.product AS product ON orderitem.productid = product.id
        ///WHERE orders.id = @id;.
        /// </summary>
        internal static string GetOrderItems {
            get {
                return ResourceManager.GetString("GetOrderItems", resourceCulture);
            }
        }
    }
}
